name: Deployment

on:
  workflow_dispatch:
    inputs:
      level:
        description: Version bump level
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

env:
  local-path: config
  store-builds: 5

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out repository
        uses: actions/checkout@v3

      - name: ðŸ”’ Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          cat > ~/.ssh/config <<'EOF'
          Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
          EOF

      - name: âš™ï¸ Update Home Assistant configuration
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }} "
            iocage console homeassistant
            su - homeassistant
            source ${{ secrets.VENV_DIRECTORY }}/bin/activate
            cd ${{ secrets.CONFIG_DIRECTORY }}
            git fetch
            git checkout ${{ github.sha }}
            chown -R ${{ secrets.USER }}:${{ secrets.GROUP }} .
          "

      - name: â™»ï¸ Snapshot iocage jail
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }} "
            iocage snapshot homeassistant
          "

      - name: ðŸŽ¬ Restart service
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }} "
            iocage restart homeassistant
          "

  create-release:
    name: Create Release
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ github.event.inputs.level }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          name: Release ${{ steps.bump-semver.outputs.new_version }}
          draft: false
